# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Breizhzion.NoiseCrypt
PackageVersion: 0.7.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
UpgradeBehavior: install
ProductCode: '{7D3F1A62-4C58-4E71-9B0D-2A6E5C8F41B3}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/bzhzion/noisecrypt/releases/download/v0.7.0/NoiseCrypt-0.7.0-amd64-setup.exe
  InstallerSha256: 2E3F59D841A05CA47F1833BC2CE24CCC5ABF6BB799BDA764577BDDA55852580D
- Architecture: arm64
  InstallerUrl: https://github.com/bzhzion/noisecrypt/releases/download/v0.7.0/NoiseCrypt-0.7.0-arm64-setup.exe
  InstallerSha256: 2B01DD8CF2494733E4F6693192B3C5DADD87CB4A1CDC875EE1D6CE93FD0E3F58
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-09-08
