# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Breizhzion.Hublot
PackageVersion: 0.1.8
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
UpgradeBehavior: install
ProductCode: '{3F1A9C2E-6B4D-4F8A-9E3C-1D2B5A7C8E4F}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://dl.breizhzion.com/hublot/Hublot-Setup-x64-0.1.8.exe
  InstallerSha256: 4DBF1A3DCD4B1132E0AC03A63B721FC916C4A5CD2CBF24BA65B51F7D420E748E
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-09-26
